/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stdio.h"
#include "main.h"
#include "beep.h"
#include "config.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)

#define ID_TEXT_GUIDE0  (GUI_ID_USER + 0x01)
#define ID_TEXT_GUIDE1  (GUI_ID_USER + 0x02)
#define ID_TEXT_GUIDE2  (GUI_ID_USER + 0x03)
#define ID_LISTVIEW_0   (GUI_ID_USER + 0x04)

#define ID_TEXT_VOLT_INFO    (GUI_ID_USER + 0x05)
#define ID_TEXT_VOLT_VALUE   (GUI_ID_USER + 0x06)

#define ID_TEXT_PROGRESS     (GUI_ID_USER + 0x07)
#define ID_PROGBAR_0         (GUI_ID_USER + 0x08)

#define ID_BUTTON_01mg       (GUI_ID_USER + 0x09)
#define ID_BUTTON_001mg      (GUI_ID_USER + 0x0A)
#define ID_BUTTON_0001mg     (GUI_ID_USER + 0x0B)

#define ID_BUTTON_RETURN     (GUI_ID_USER + 0x0C)

#define ID_TEXT_RESULT_INFO  (GUI_ID_USER + 0x0D)
#define ID_TEXT_RESULT_VALUE (GUI_ID_USER + 0x0E)

extern const GUI_FONT GUI_FontHZ_yahei_20;
extern const GUI_FONT GUI_FontHZ_yahei_16;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },

    { TEXT_CreateIndirect, "guide0", ID_TEXT_GUIDE0, 5, 5, 150, 25, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "guide1", ID_TEXT_GUIDE1, 5, 40, 600, 25, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "guide2", ID_TEXT_GUIDE2, 5, 75, 600, 25, 0, 0x0, 0 },

    {LISTVIEW_CreateIndirect, "lv", ID_LISTVIEW_0, 5, 110, 530, 247, 0, 0x0, 0},

    {TEXT_CreateIndirect, "实时电位:", ID_TEXT_VOLT_INFO, 5, 360, 100, 30, 0, 0x0, 0},
    {TEXT_CreateIndirect, "00.00mV", ID_TEXT_VOLT_VALUE, 120, 365, 100, 30, 0, 0x0, 0},
    
    {TEXT_CreateIndirect, "结果汇总:", ID_TEXT_RESULT_INFO, 290, 360, 100, 30, 0, 0x0, 0},
    {TEXT_CreateIndirect, "未测量", ID_TEXT_RESULT_VALUE, 410, 360, 100, 30, 0, 0x0, 0},

    {TEXT_CreateIndirect, "测量进度", ID_TEXT_PROGRESS, 5, 392, 120, 30, 0, 0x0, 0},
    {PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 120, 395, 415, 25, 0, 0x0, 0},

    {BUTTON_CreateIndirect, "开始测量", ID_BUTTON_01mg, 560, 155, 200, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "开始测量", ID_BUTTON_001mg, 560, 235, 200, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "开始测量", ID_BUTTON_0001mg, 560, 315, 200, 40, 0, 0x0, 0},

    {BUTTON_CreateIndirect, "返回", ID_BUTTON_RETURN, 680, 5, 100, 40, 0, 0x0, 0}
};

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN      hItem;
    int     NCode;
    int     Id;
    int i;
    HEADER_Handle hHeader;

    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        hItem = pMsg->hWin;
        FRAMEWIN_SetTitleHeight(hItem, 50);
        FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        FRAMEWIN_SetFont(hItem, &GUI_FontHZ_yahei_20);
        FRAMEWIN_SetTextColor(hItem, GUI_BLACK_33);
        FRAMEWIN_SetClientColor(hItem, GUI_WHITE);
        FRAMEWIN_SetText(hItem, "电极校对");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_GUIDE0);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);
        TEXT_SetText(hItem, "校对方法:");      

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_GUIDE1);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);
        TEXT_SetText(hItem, "取10ml对应浓度氨离子标准溶液至100ml容量瓶中，稀释至刻度");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_GUIDE2);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);
        TEXT_SetText(hItem, "摇匀，点击对应浓度右侧测量按钮进行测量");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
        LISTVIEW_SetRowHeight(hItem, 40);
        LISTVIEW_SetBkColor(hItem, 0, GUI_GRAY);
        LISTVIEW_SetGridVis(hItem, 1);
        LISTVIEW_SetFont(hItem, GUI_FONT_24_ASCII);
        for (i = 0; i < 5; i++)
            LISTVIEW_AddRow(hItem, NULL);

        hHeader = LISTVIEW_GetHeader(hItem);
        HEADER_SetFont(hHeader, &GUI_FontHZ_yahei_16);
        HEADER_SetTextColor(hHeader, GUI_BLACK_33);
        HEADER_SetHeight(hHeader, 45);
        HEADER_SetBkColor(hHeader, GUI_GREEN);
        LISTVIEW_AddColumn(hItem, 170, "溶液浓度", GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_AddColumn(hItem, 120, "电极电位", GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_AddColumn(hItem, 120, "电极斜率", GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_AddColumn(hItem, 120, "测试结果", GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_SetTextColor(hItem, 0, GUI_BLACK_33);
        LISTVIEW_SetItemText(hItem, 0, 0, "0.1mg/ml");
        LISTVIEW_SetItemText(hItem, 0, 2, "0.01mg/ml");
        LISTVIEW_SetItemText(hItem, 0, 4, "0.001mg/ml");
        LISTVIEW_SetItemText(hItem, 1, 0, "----");
        LISTVIEW_SetItemText(hItem, 1, 2, "----");
        LISTVIEW_SetItemText(hItem, 1, 4, "----");
        LISTVIEW_SetItemText(hItem, 2, 1, "----");
        LISTVIEW_SetItemText(hItem, 2, 3, "----");
        LISTVIEW_SetItemText(hItem, 3, 1, "----");
        LISTVIEW_SetItemText(hItem, 3, 3, "----");

        // realtime volt
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VOLT_INFO);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VOLT_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_GREEN);

        // result
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_VALUE);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_RED);

        // test progress
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PROGRESS);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);        

        hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
        PROGBAR_SetFont(hItem, GUI_FONT_24_ASCII);
        PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
        PROGBAR_SetSkinClassic(hItem);
        PROGBAR_SetMinMax(hItem, 0, 100);
        PROGBAR_SetValue(hItem, 50);

        // button
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_01mg);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKBLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_001mg);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKBLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0001mg);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKBLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKRED);

    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id) {
        default:
            break;
        }
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
int ui_check_creat(void)
{
    return GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
