/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "beep.h"
#include "main.h"
#include "string.h"
#include "stdio.h"
#include "ui_diag.h"
#include "report.h"
#include "data.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_HEAD    (GUI_ID_USER + 0x01)
#define ID_IMAGE_0      (GUI_ID_USER + 0x02)

#define ID_TEXT_ITEM1   (GUI_ID_USER + 0x03)
#define ID_TEXT_ITEM2   (GUI_ID_USER + 0x04)
#define ID_TEXT_ITEM3   (GUI_ID_USER + 0x05)
#define ID_TEXT_ITEM4   (GUI_ID_USER + 0x06)
#define ID_TEXT_ITEM5   (GUI_ID_USER + 0x07)
#define ID_TEXT_ITEM6   (GUI_ID_USER + 0x08)
#define ID_TEXT_ITEM7   (GUI_ID_USER + 0x09)
#define ID_TEXT_ITEM8   (GUI_ID_USER + 0x0a)

#define ID_TEXT_VALUE1  (GUI_ID_USER + 0x0b)
#define ID_TEXT_VALUE2  (GUI_ID_USER + 0x0c)
#define ID_TEXT_VALUE3  (GUI_ID_USER + 0x0d)
#define ID_TEXT_VALUE4  (GUI_ID_USER + 0x0e)
#define ID_TEXT_VALUE5  (GUI_ID_USER + 0x0f)
#define ID_TEXT_VALUE6  (GUI_ID_USER + 0x10)
#define ID_TEXT_VALUE7  (GUI_ID_USER + 0x11)
#define ID_TEXT_VALUE8  (GUI_ID_USER + 0x12)

#define ID_BUTTON_PRINT (GUI_ID_USER + 0x13)
#define ID_BUTTON_QUIT  (GUI_ID_USER + 0x14)

extern const GUI_FONT GUI_FontHZ_yahei_16;
extern const GUI_BITMAP bminfor_32px;

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 150, 70, 500, 360, 0, 0x0, 0},
    {IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 5, 5, 32, 32, 0, 0, 0},
    {TEXT_CreateIndirect, "header", ID_TEXT_HEAD, 52, 5, 200, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line1", ID_TEXT_ITEM1, 10, 50, 300, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "value1", ID_TEXT_VALUE1,320, 50, 100, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line2", ID_TEXT_ITEM2, 10, 80, 300, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "value2", ID_TEXT_VALUE2,320, 80, 100, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line3", ID_TEXT_ITEM3, 10, 110, 300, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "value3", ID_TEXT_VALUE3,320, 110, 100, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line4", ID_TEXT_ITEM4, 10, 140, 300, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "value4", ID_TEXT_VALUE4,320, 140, 100, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line5", ID_TEXT_ITEM5, 10, 170, 300, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "value5", ID_TEXT_VALUE5,320, 170, 100, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line6", ID_TEXT_ITEM6, 10, 200, 300, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "value6", ID_TEXT_VALUE6, 320, 200, 100, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line7", ID_TEXT_ITEM7, 10, 230, 300, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "value7", ID_TEXT_VALUE7, 320, 230, 100, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line8", ID_TEXT_ITEM8, 10, 260, 300, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "value8", ID_TEXT_VALUE8, 320, 260, 100, 25, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "´òÓ¡", ID_BUTTON_PRINT, 20, 310, 140, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Íê³É", ID_BUTTON_QUIT, 340, 310, 140, 40, 0, 0x0, 0},
    // USER START (Optionally insert additional widgets)
    // USER END
};

struct diag_result g_diag_res;

static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    int i;
    struct test_data *td = data_obj();
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKBLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEAD);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        if (g_diag_start.header)
            TEXT_SetText(hItem, g_diag_res.header);
        else
            WM_HideWindow(hItem);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
        IMAGE_SetBitmap(hItem, &bminfor_32px);

        for (i = 0; i < g_diag_res.cnt; i++) {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ITEM1 + i);
            TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
            TEXT_SetTextColor(hItem, GUI_WHITE);
            TEXT_SetText(hItem, g_diag_res.items[i].item);

            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VALUE1 + i);
            TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
            TEXT_SetTextColor(hItem, GUI_WHITE);
            TEXT_SetText(hItem, g_diag_res.items[i].value);
        }

        for (; i < RESULT_ITEMS_MAX; i++) {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ITEM1 + i);
            WM_HideWindow(hItem);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VALUE1 + i);
            WM_HideWindow(hItem);
        }

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_QUIT);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_PRINT: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_TEXT_HEAD, ID_BUTTON_QUIT, 0);
                WM_Exec();
                //test_print_result();
                report_show(td);
                test_enable_all_items(pMsg->hWin, ID_TEXT_HEAD, ID_BUTTON_QUIT, 1);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_QUIT: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                beep_clicked();
                GUI_EndDialog(pMsg->hWin, 0);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

int diag_result_creat(void)
{
    return GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
