/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "main.h"
#include "stdio.h"
#include "FreeRTOS.h"
#include "task.h"
#include "beep.h"
#include "data.h"
#include "string.h"
#include "report.h"
#include "ui_diag.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0            (GUI_ID_USER + 0x00)
#define ID_BUTTON_RETURN       (GUI_ID_USER + 0x01)
#define ID_BUTTON_PRINT        (GUI_ID_USER + 0x02)

#define ID_TEXT_DATE           (GUI_ID_USER + 0x03)
#define ID_TEXT_DATE_VALUE     (GUI_ID_USER + 0x04)

#define ID_TEXT_IDX            (GUI_ID_USER + 0x05)
#define ID_TEXT_IDX_VALUE      (GUI_ID_USER + 0x06)

#define ID_TEXT_WEIGHT         (GUI_ID_USER + 0x07)
#define ID_TEXT_WEIGHT_VALUE   (GUI_ID_USER + 0x08)

#define ID_TEXT_VOLUME         (GUI_ID_USER + 0x09)
#define ID_TEXT_VOLUME_VALUE   (GUI_ID_USER + 0x0a)

#define ID_TEXT_BLOCK1         (GUI_ID_USER + 0x0b)
#define ID_TEXT_BLOCK1_VOLT    (GUI_ID_USER + 0x0c)

#define ID_TEXT_BLOCK2         (GUI_ID_USER + 0x0d)
#define ID_TEXT_BLOCK2_VOLT    (GUI_ID_USER + 0x1e)

#define ID_TEXT_BLOCK_AVG      (GUI_ID_USER + 0x0f)
#define ID_TEXT_BLOCK_AVG_VOLT (GUI_ID_USER + 0x10)

#define ID_TEXT_SAMPLE         (GUI_ID_USER + 0x11)
#define ID_TEXT_SAMPLE_VOLT    (GUI_ID_USER + 0x12)

#define ID_TEXT_RESULT         (GUI_ID_USER + 0x13)
#define ID_TEXT_RESULT_VALUE   (GUI_ID_USER + 0x14)

#define ID_TEXT_HEADER         (GUI_ID_USER + 0x15)

// USER START (Optionally insert additional defines)
extern const GUI_FONT GUI_FontHZ_yahei_20;
extern const GUI_FONT GUI_FontHZ_yahei_16;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
struct diag_detail g_diag_detail;
static struct test_data data;
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0},

    {TEXT_CreateIndirect, "数据处理", ID_TEXT_HEADER, 300, 2, 200, 40, 0, 0x0, 0},

    {TEXT_CreateIndirect, "序号：", ID_TEXT_IDX, 10, 60, 40, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_IDX_VALUE, 60, 60, 40, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "时间：", ID_TEXT_DATE, 10, 90, 40, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_DATE_VALUE, 60, 90, 200, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "试样质量：", ID_TEXT_WEIGHT, 10, 120, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_WEIGHT_VALUE, 100, 120, 200, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "滤液体积：", ID_TEXT_VOLUME, 10, 150, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_VOLUME_VALUE, 100, 150, 200, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "空白实验1电极电位：", ID_TEXT_BLOCK1, 10, 180, 200, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_BLOCK1_VOLT, 220, 180, 200, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "空白实验2电极电位：", ID_TEXT_BLOCK2, 10, 210, 200, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_BLOCK2_VOLT, 220, 210, 200, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "空白实验平均电极电位：", ID_TEXT_BLOCK_AVG, 10, 240, 200, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_BLOCK_AVG_VOLT, 220, 240, 200, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "试样电极电位：", ID_TEXT_SAMPLE, 10, 270, 200, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_SAMPLE_VOLT, 220, 270, 200, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "氨离子含量：", ID_TEXT_RESULT, 10, 320, 200, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "0", ID_TEXT_RESULT_VALUE, 220, 320, 200, 25, 0, 0x64, 0},

    {BUTTON_CreateIndirect, "打印", ID_BUTTON_PRINT, 610, 420, 180, 50, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "返回", ID_BUTTON_RETURN, 640, 80, 140, 60, 0, 0x0, 0},
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id, res;
    char buf[32];

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_20);
        TEXT_SetTextColor(hItem, GUI_DARKBLUE);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, 0, GUI_RED);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_IDX);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_DATE);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WEIGHT);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VOLUME);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCK1);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCK2);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCK_AVG);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SAMPLE);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        res = data_read(&data, g_diag_detail.data_idx);
        if (!res) {
            g_diag_ok.header = "错误";
            g_diag_ok.str_lin1 = "数据加载错误，无效的数据校验";
            g_diag_ok.str_lin2 = NULL;
            g_diag_ok.str_lin3 = NULL;
            diag_ok_creat();
            g_ui_msg.msg = UI_MSG_LOAD_DATA;
            GUI_EndDialog(pMsg->hWin, 0);
            break;
        }

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_DATE_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "20%02d-%02d-%02d      %02d:%02d",
            data.year, data.month, data.day,
            data.hour, data.minute);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_IDX_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%03d", data.index);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WEIGHT_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.3fg", data.weight_sample);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VOLUME_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.2fmL", data.volume_sample);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCK1_VOLT);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.2fmV", data.volt_block1);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCK2_VOLT);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.2fmV", data.volt_block2);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCK_AVG_VOLT);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.2fmV", data.volt_blockagv);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SAMPLE_VOLT);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.2fmV", data.volt_sample);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.2fmg/kg", data.result);
        TEXT_SetText(hItem, buf);
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_BUTTON_RETURN: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                beep_clicked();
                g_ui_msg.msg = UI_MSG_LOAD_DATA;
                GUI_EndDialog(pMsg->hWin, 0);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        //case ID_BUTTON_EXP: // Notifications sent by 'Button'
        //    switch (NCode)
        //    {
        //    case WM_NOTIFICATION_CLICKED:
        //        // USER START (Optionally insert code for reacting on notification message)
        //        beep_clicked();
        //        // USER END
        //        break;
        //    case WM_NOTIFICATION_RELEASED:
        //        // USER START (Optionally insert code for reacting on notification message)
        //        // USER END
        //        break;
        //        // USER START (Optionally insert additional code for further notification handling)
        //        // USER END
        //    }
        //    break;
        case ID_BUTTON_PRINT: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_BUTTON_RETURN, ID_TEXT_HEADER, 0);
                WM_Exec();
                report_show(&data);
                test_enable_all_items(pMsg->hWin, ID_BUTTON_RETURN, ID_TEXT_HEADER, 1);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

int ui_detail_creat(void)
{
    return GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
