/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "WM.h"
#include "stdio.h"
#include "main.h"
#include "beep.h"
#include "config.h"
#include "ui_diag.h"
#include "test.h"
#include "ad770x.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0       (GUI_ID_USER + 0x00)

#define ID_GRAPH_0          (GUI_ID_USER + 0x01)

#define ID_TEXT_WEIGHT      (GUI_ID_USER + 0x02)
#define ID_EDIT_WEIGHT      (GUI_ID_USER + 0x03)

#define ID_TEXT_VOLUME      (GUI_ID_USER + 0x04)
#define ID_EDIT_VOLUME      (GUI_ID_USER + 0x05)

#define ID_TEXT_BLOCKTEST1  (GUI_ID_USER + 0x06)
#define ID_EDIT_BLOCKTEST1  (GUI_ID_USER + 0x07)

#define ID_TEXT_BLOCKTEST2  (GUI_ID_USER + 0x08)
#define ID_EDIT_BLOCKTEST2  (GUI_ID_USER + 0x09)

#define ID_TEXT_VOLT_INFO   (GUI_ID_USER + 0x0A)
#define ID_TEXT_VOLT_VALUE  (GUI_ID_USER + 0x0B)

#define ID_TEXT_PROGRESS    (GUI_ID_USER + 0x0C)
#define ID_PROGBAR_0        (GUI_ID_USER + 0x0D)

#define ID_TEXT_BLOCKTEST_VOLT_INFO      (GUI_ID_USER + 0x0E)
#define ID_TEXT_BLOCKTEST_VOLT_VALUE     (GUI_ID_USER + 0x0F)

#define ID_TEXT_TEST_VOLT_INFO           (GUI_ID_USER + 0x10)
#define ID_TEXT_TEST_VOLT_VALUE          (GUI_ID_USER + 0x11)


#define ID_BUTTON_BLOCKTEST1    (GUI_ID_USER + 0x12)
#define ID_BUTTON_BLOCKTEST2    (GUI_ID_USER + 0x13)
#define ID_BUTTON_TEST          (GUI_ID_USER + 0x14)

#define ID_BUTTON_RETURN        (GUI_ID_USER + 0x15)

#define ID_TEXT_HEADER          (GUI_ID_USER + 0x16)

enum run_flags{
    RUN_IDLE = 0x0,
    RUN_BLOCK1,
    RUN_BLOCK2,
    RUN_TEST
};

struct test_ctrl {
    int block1_finished;
    int block2_finished;
    int block_ready;
};

extern const GUI_FONT GUI_FontHZ_yahei_20;
extern const GUI_FONT GUI_FontHZ_yahei_16;
// USER END

static GRAPH_SCALE_Handle hScaleV, hScaleH;
static GRAPH_DATA_Handle pdataGRP;
static WM_HWIN wait_diag_handle;
static char strbuf[32];
struct test_data g_td;
struct test_ctrl tctrl;
static float volt = 0.0;
static int run_flag = RUN_IDLE;
static int run_cnt = TEST_LAST_CNT;
static GUI_POINT point = {0, 0};
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
    {TEXT_CreateIndirect, "离子分析", ID_TEXT_HEADER, 300, 2, 200, 40, 0, 0x0, 0},

    {GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 2, 52, 300, 385, 0, 0x0, 0 },

    {TEXT_CreateIndirect, "实时电位:", ID_TEXT_VOLT_INFO, 5, 442, 100, 30, 0, 0x0, 0},
    {TEXT_CreateIndirect, "00.00mV", ID_TEXT_VOLT_VALUE, 120, 445, 100, 30, 0, 0x0, 0},

    {TEXT_CreateIndirect, "试样质量", ID_TEXT_WEIGHT, 310, 55, 100, 30, 0, 0x0, 0},
    {EDIT_CreateIndirect, "10.000g", ID_EDIT_WEIGHT, 500, 55, 150, 30, 0, 0x0, 0},

    {TEXT_CreateIndirect, "滤液体积", ID_TEXT_VOLUME, 310, 105, 100, 30, 0, 0x0, 0},
    {EDIT_CreateIndirect, "20.00mL", ID_EDIT_VOLUME, 500, 105, 150, 30, 0, 0x0, 0},

    {TEXT_CreateIndirect, "空白实验1电极电位", ID_TEXT_BLOCKTEST1, 310, 155, 190, 30, 0, 0x0, 0 },
    {EDIT_CreateIndirect, "0.00mV", ID_EDIT_BLOCKTEST1, 500, 155, 150, 30, 0, 0x0, 0},

    {TEXT_CreateIndirect, "空白实验2电极电位", ID_TEXT_BLOCKTEST2, 310, 205, 190, 30, 0, 0x0, 0 },
    {EDIT_CreateIndirect, "0.00mV", ID_EDIT_BLOCKTEST2, 500, 205, 150, 30, 0, 0x0, 0},
    
    {TEXT_CreateIndirect, "空白实验平均电极电位:", ID_TEXT_BLOCKTEST_VOLT_INFO, 310, 270, 220, 30, 0, 0x0, 0},
    {TEXT_CreateIndirect, "00.00mV", ID_TEXT_BLOCKTEST_VOLT_VALUE, 555, 270, 100, 30, 0, 0x0, 0},

    {TEXT_CreateIndirect, "离子分析电极电位:", ID_TEXT_TEST_VOLT_INFO, 310, 310, 220, 30, 0, 0x0, 0},
    {TEXT_CreateIndirect, "00.00mV", ID_TEXT_TEST_VOLT_VALUE, 555, 310, 100, 30, 0, 0x0, 0},

    {BUTTON_CreateIndirect, "空白实验1", ID_BUTTON_BLOCKTEST1, 320, 370, 120, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "空白实验2", ID_BUTTON_BLOCKTEST2, 480, 370, 120, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "离子分析", ID_BUTTON_TEST, 640, 370, 120, 40, 0, 0x0, 0},

    {TEXT_CreateIndirect, "测试进度", ID_TEXT_PROGRESS, 310, 442, 100, 30, 0, 0x0, 0},
    {PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 410, 445, 360, 25, 0, 0x0, 0},

    {BUTTON_CreateIndirect, "返回", ID_BUTTON_RETURN, 715, 5, 80, 40, 0, 0x0, 0}
};

// USER START (Optionally insert additional static code)
// USER END

static void graph_clear(void)
{
    GRAPH_DATA_XY_Clear(pdataGRP);
    GRAPH_SCALE_SetOff(hScaleH, 0);
    GRAPH_DATA_XY_SetOffX(pdataGRP, 0);
    point.x = 0;
}

static void update_block_volt(WM_HWIN hWin)
{
    WM_HWIN hItem;
    char buf[32];
    
    if (tctrl.block1_finished && tctrl.block2_finished) {
        g_td.volt_blockagv = (g_td.volt_block1 + g_td.volt_block2) / 2;
        tctrl.block_ready++;
        hItem = WM_GetDialogItem(hWin, ID_TEXT_BLOCKTEST_VOLT_VALUE);
        sprintf(buf, TEST_VOLT_FMT, g_td.volt_blockagv);
        TEXT_SetText(hItem, buf);
    }
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN      hItem;
    int     NCode;
    int     Id;
    char    *p;
    int     result;

    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        hItem = pMsg->hWin;
        WM_CreateTimer(hItem, 0, 1000, 0);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HEADER);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_20);
        TEXT_SetTextColor(hItem, GUI_DARKBLUE);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
        GRAPH_SetBorder(hItem, 25, 2, 3, 15);
        GRAPH_SetGridVis(hItem, 2);
        GRAPH_SetGridFixedX(hItem, 2);
        GRAPH_SetGridDistY(hItem, 20);
        GRAPH_SetGridDistX(hItem, 25);

        hScaleV = GRAPH_SCALE_Create(5, GUI_TA_LEFT, GRAPH_SCALE_CF_VERTICAL, 20);
        GRAPH_SCALE_SetTextColor(hScaleV, GUI_RED);
        GRAPH_SCALE_SetOff(hScaleV, 20);
        GRAPH_AttachScale(hItem, hScaleV);
        
        hScaleH = GRAPH_SCALE_Create(375, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 50);
        GRAPH_SCALE_SetTextColor(hScaleH, GUI_DARKGREEN);
        GRAPH_AttachScale(hItem, hScaleH);
        pdataGRP = GRAPH_DATA_XY_Create(GUI_DARKGREEN, 100, 0, 0);
        GRAPH_DATA_XY_SetOffY(pdataGRP, 20);
        GRAPH_AttachData(hItem, pdataGRP);
        GRAPH_DATA_XY_Clear(pdataGRP);

        // realtime volt
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VOLT_INFO);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VOLT_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_DARKGREEN);

        // weight
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WEIGHT);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_WEIGHT);
        EDIT_SetTextColor(hItem, EDIT_CI_ENABELD, GUI_DARKGREEN);
        EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        EDIT_SetText(hItem, "10.000g");

        // volume
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VOLUME);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_VOLUME);
        EDIT_SetTextColor(hItem, EDIT_CI_ENABELD, GUI_DARKGREEN);
        EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        EDIT_SetText(hItem, "20.00ml");

        // block test 1
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCKTEST1);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BLOCKTEST1);
        EDIT_SetTextColor(hItem, EDIT_CI_ENABELD, GUI_DARKGREEN);
        EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        EDIT_SetText(hItem, "00.00mV");

        // block test 2
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCKTEST2);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BLOCKTEST2);
        EDIT_SetTextColor(hItem, EDIT_CI_ENABELD, GUI_DARKGREEN);
        EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        EDIT_SetText(hItem, "00.00mV");

        // block test average
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCKTEST_VOLT_INFO);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BLOCKTEST_VOLT_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_DARKGREEN);

        // test volt
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TEST_VOLT_INFO);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TEST_VOLT_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_DARKGREEN);

        // button
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_BLOCKTEST1);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKBLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_BLOCKTEST2);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKBLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_TEST);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKBLUE);

        // test progress
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PROGRESS);
        TEXT_SetFont(hItem, &GUI_FontHZ_yahei_16);
        TEXT_SetTextColor(hItem, GUI_BLACK_33);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
        PROGBAR_SetFont(hItem, GUI_FONT_24_ASCII);
        PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
        PROGBAR_SetSkinClassic(hItem);
        PROGBAR_SetMinMax(hItem, 0, 100);
        PROGBAR_SetValue(hItem, 0);

        // return
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
        BUTTON_SetFont(hItem, &GUI_FontHZ_yahei_16);
        BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKRED);

        g_td.volume_sample = 20.00;
        g_td.weight_sample = 10.000;

        tctrl.block1_finished = 0;
        tctrl.block2_finished = 0;
        tctrl.block_ready = 0;
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id) {
        case ID_EDIT_WEIGHT:
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 0);
                WM_Exec();
                if (numpad_creat()) {
                    p = numpad_get();
                    sscanf(p, "%f", &g_td.weight_sample);
                    sprintf(strbuf, "%.3fg", g_td.weight_sample);
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_WEIGHT);
                    EDIT_SetText(hItem, strbuf);
                }
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                break;
            default:
                break;
            }
            break;
        case ID_EDIT_VOLUME:
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 0);
                WM_Exec();
                if (numpad_creat()) {
                    p = numpad_get();
                    sscanf(p, "%f", &g_td.volume_sample);
                    sprintf(strbuf, "%.2fml", g_td.volume_sample);
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_VOLUME);
                    EDIT_SetText(hItem, strbuf);
                }
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                break;
            default:
                break;
            }
            break;
        case ID_EDIT_BLOCKTEST1:
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 0);
                WM_Exec();
                if (numpad_creat()) {
                    p = numpad_get();
                    sscanf(p, "%f", &g_td.volt_block1);
                    sprintf(strbuf, TEST_VOLT_FMT, g_td.volt_block1);
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BLOCKTEST1);
                    EDIT_SetText(hItem, strbuf);
                    tctrl.block1_finished++;
                    update_block_volt(pMsg->hWin);
                }
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                break;
            default:
                break;
            }
            break;
        case ID_EDIT_BLOCKTEST2:
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 0);
                WM_Exec();
                if (numpad_creat()) {
                    p = numpad_get();
                    sscanf(p, "%f", &g_td.volt_block2);
                    sprintf(strbuf, TEST_VOLT_FMT, g_td.volt_block2);
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BLOCKTEST2);
                    EDIT_SetText(hItem, strbuf);
                    tctrl.block2_finished++;
                    update_block_volt(pMsg->hWin);
                }
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                break;
            default:
                break;
            }
            break;
        case ID_BUTTON_RETURN:
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                beep_clicked();
                printf("run main menu\r\n");
                g_ui_msg.msg = UI_MSG_LOAD_MENU;
                GUI_EndDialog(pMsg->hWin, 0);
                break;
            default:
                break;
            }
            break;
        case ID_BUTTON_BLOCKTEST1:
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 0);
                WM_Exec();
                g_diag_start.header = "提示";
                g_diag_start.str_lin1 = "即将进行空白实验1";
                g_diag_start.str_lin2 = "请将空白试样放置到试样台,并启动磁力搅拌器";
                g_diag_start.str_lin3 = "准备好后,点击开始实验以启动检测";
                result = diag_start_creat();
                if (result)
                    test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                else {
                    graph_clear();
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
                    PROGBAR_SetValue(hItem, 0);
                    run_cnt = TEST_LAST_CNT;
                    run_flag = RUN_BLOCK1;
                    g_diag_wait.header = "提示";
                    g_diag_wait.str_lin1 = "正在进行空白实验1";
                    g_diag_wait.str_lin2 = NULL;
                    g_diag_wait.str_lin3 = "请稍后......";
                    wait_diag_handle = diag_wait_creat(320);
                    GUI_ExecCreatedDialog(wait_diag_handle);
                }
                break;
            default:
                break;
            }
            break;
        case ID_BUTTON_BLOCKTEST2:
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 0);
                WM_Exec();
                g_diag_start.header = "提示";
                g_diag_start.str_lin1 = "即将进行空白实验2";
                g_diag_start.str_lin2 = "请将空白试样放置到试样台,并启动磁力搅拌器";
                g_diag_start.str_lin3 = "准备好后,点击开始实验以启动检测";
                result = diag_start_creat();
                if (result)
                    test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                else {
                    graph_clear();
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
                    PROGBAR_SetValue(hItem, 0);
                    run_cnt = TEST_LAST_CNT;
                    run_flag = RUN_BLOCK2;
                }
                break;
            default:
                break;
            }
            break;
        case ID_BUTTON_TEST:
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                beep_clicked();
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 0);
                WM_Exec();

                if (tctrl.block_ready) {
                    g_diag_start.header = "提示";
                    g_diag_start.str_lin1 = "即将进行离子分析";
                    g_diag_start.str_lin2 = "请将空白试样放置到试样台,并启动磁力搅拌器";
                    g_diag_start.str_lin3 = "准备好后,点击开始实验以启动检测";
                    result = diag_start_creat();
                    if (result)
                        test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                    else {
                        graph_clear();
                        hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
                        PROGBAR_SetValue(hItem, 0);
                        run_cnt = TEST_LAST_CNT;
                        run_flag = RUN_TEST;
                    }
                } else {
                    g_diag_ok.header = "提示";
                    g_diag_ok.str_lin1 = "无法进行氨离子测量";
                    g_diag_ok.str_lin2 = "请先进行空白实验或输入空白实验电压值";
                    g_diag_ok.str_lin3 = NULL;
                    diag_ok_creat();
                    test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    case WM_TIMER:
        if (run_flag != RUN_IDLE) {
            run_cnt--;
            hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
            PROGBAR_SetValue(hItem, test_progress(run_cnt));
            volt = test_volt_get(); // take some time
            WM_Exec();

            if (run_cnt <= 0) {
                beep_finished();
                switch (run_flag) {
                case RUN_BLOCK1:
                    g_td.volt_block1 = volt;
                    tctrl.block1_finished++;
                    update_block_volt(pMsg->hWin);
                    g_diag_ok.header = "空白实验1";
                    g_diag_ok.str_lin1 = "完成空白实验1,采集到电压值为:";
                    sprintf(strbuf, TEST_VOLT_FMT, volt);
                    g_diag_ok.str_lin2 = strbuf;
                    g_diag_ok.str_lin3 = NULL;
                    diag_ok_creat();
                    break;
                case RUN_BLOCK2:
                    g_td.volt_block2 = volt;
                    tctrl.block1_finished++;
                    update_block_volt(pMsg->hWin);
                    g_diag_ok.header = "空白实验2";
                    g_diag_ok.str_lin1 = "完成空白实验2,采集到电压值为:";
                    sprintf(strbuf, TEST_VOLT_FMT, volt);
                    g_diag_ok.str_lin2 = strbuf;
                    g_diag_ok.str_lin3 = NULL;
                    diag_ok_creat();
                    break;
                case RUN_TEST:
                    g_td.volt_sample = volt;
                    g_diag_res.cnt = 7;
                    g_diag_res.header = "分析结果";
                    g_diag_res.items[0].item = "试样质量：";
                    sprintf(g_diag_res.items[0].value, "%.3fg", g_td.weight_sample);
                    g_diag_res.items[1].item = "滤液体积：";
                    sprintf(g_diag_res.items[1].value, "%.2fmL", g_td.volume_sample);
                    g_diag_res.items[2].item = "空白实验1电极电位：";
                    sprintf(g_diag_res.items[2].value, "%.2fmV", g_td.volt_block1);
                    g_diag_res.items[3].item = "空白实验2电极电位：";
                    sprintf(g_diag_res.items[3].value, "%.2fmV", g_td.volt_block2);
                    g_diag_res.items[4].item = "空白实验平均电极电位：";
                    sprintf(g_diag_res.items[4].value, "%.2fmV", g_td.volt_blockagv);
                    g_diag_res.items[5].item = "离子分析电极电位：";
                    sprintf(g_diag_res.items[5].value, "%.2fmV", g_td.volt_sample);
                    g_diag_res.items[6].item = "氨离子含量：";
                    sprintf(g_diag_res.items[6].value, "%.2fmg/kg", g_td.result);
                    diag_result_creat();
                    break;
                default:
                    break;
                }
                test_enable_all_items(pMsg->hWin, ID_GRAPH_0, ID_TEXT_HEADER, 1);
                run_flag = RUN_IDLE;
                GUI_EndDialog(wait_diag_handle, 0);
            } else
                beep_clicked();
        } else
            volt = ad7705_read();

        sprintf(strbuf, TEST_VOLT_FMT, volt);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VOLT_VALUE);
        TEXT_SetText(hItem, strbuf);

        if (point.x > 250)
            graph_clear();

        point.y = (int)volt;
        GRAPH_DATA_XY_AddPoint(pdataGRP, &point);
        point.x += 10;

        WM_RestartTimer(pMsg->Data.v, 1000);
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
int ui_test_creat(void)
{
    return GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
